require("options")
require("plugins")

require("configs.nvim-lsp")
require("configs.nvim-lualine")
require("configs.nvim-tree")
require("configs.nvim-telescope")
require("configs.nvim-gitsigns")
require("configs.nvim-colorizer")
require("configs.nvim-comment")
require("configs.nvim-marks")
require("configs.nvim-autopairs")
require("configs.nvim-cmp")
require("configs.nvim-null-ls")
require("configs.nvim-treesitter")

require("diagnostics")
require("keymaps")
