require("options")
require("plugins")

require("configs.nvim-gruvbox")
require("configs.nvim-lsp")
require("configs.nvim-lualine")
require("configs.nvim-tree")
require("configs.nvim-telescope")
require("configs.nvim-gitsigns")
require("configs.nvim-colorizer")
require("configs.nvim-comment")
require("configs.nvim-marks")
-- require("configs.nvim-autopairs")
require("configs.tree-sitter-manager")
require("configs.nvim-conform")
require("configs.nvim-abolish")
require("configs.nvim-codeium")
require("configs.nvim-copilot")
require("configs.nvim-opencode")
require("configs.nvim-snacks")
require("configs.nvim-venv-selector")
require("configs.nvim-editorconfig")
require("configs.nvim-cmp")
require("configs.nvim-manson")
-- require("configs.nvim-fidget")
require("configs.nvim-auto-session")

require("diagnostics")
require("keymaps")
